[input]
base_directory = "/home/leo/devel/thebabelcat/pelican/output"
url_prefix = "thebabelcat.github.io"
html_selector = "section#content"
[[input.files]]
path = "kaos-05.html"
url = "kaos-05.html"
title = "KAOS 05"

[[input.files]]
path = "kaos-03.html"
url = "kaos-03.html"
title = "KAOS 03"

[[input.files]]
path = "kaos-04.html"
url = "kaos-04.html"
title = "KAOS 04"

[[input.files]]
path = "kaos-02.html"
url = "kaos-02.html"
title = "KAOS 02"

[[input.files]]
path = "kaos-01.html"
url = "kaos-01.html"
title = "KAOS 01"

[[input.files]]
path = "ed-e-solo-l-inizio.html"
url = "ed-e-solo-l-inizio.html"
title = "Ed è solo l'inizio"

[[input.files]]
path = "pane-burroughs-e-marmellata.html"
url = "pane-burroughs-e-marmellata.html"
title = "Pane, Burroughs e marmellata"

[[input.files]]
path = "due-supertitoli-quasi-sbagliati.html"
url = "due-supertitoli-quasi-sbagliati.html"
title = "Due supertitoli quasi sbagliati"

[[input.files]]
path = "la-sottile-scatola-rossa.html"
url = "la-sottile-scatola-rossa.html"
title = "La sottile scatola rossa"

[[input.files]]
path = "luck-tales.html"
url = "luck-tales.html"
title = "Luck Tales!"

[[input.files]]
path = "the-call-of-the-original.html"
url = "the-call-of-the-original.html"
title = "The Call of the Original"

[[input.files]]
path = "lego-il-traduttore.html"
url = "lego-il-traduttore.html"
title = "LEGO il traduttore e lo frusto"

[[input.files]]
path = "pavoni-haggis-e-champagne.html"
url = "pavoni-haggis-e-champagne.html"
title = "Pavoni, haggis e champagne"

[[input.files]]
path = "another-one-bites-the-stair.html"
url = "another-one-bites-the-stair.html"
title = "Another one bites the... stair."

[[input.files]]
path = "investire-nei-titoli.html"
url = "investire-nei-titoli.html"
title = "Investire nei titoli"

[[input.files]]
path = "l-angolo-del-tradittore.html"
url = "l-angolo-del-tradittore.html"
title = "L'angolo dei tradittore"

[[input.files]]
path = "ma-cio-che-e-futuro-sara-passato.html"
url = "ma-cio-che-e-futuro-sara-passato.html"
title = "Ma ciò che era futuro sarà passato?"

[[input.files]]
path = "sugli-accenti-persi-indiana-jones.html"
url = "sugli-accenti-persi-indiana-jones.html"
title = "Sugli accenti persi: Indiana Jones e l'ultima crociata"

[[input.files]]
path = "you-cannot-pass-or-shall.html"
url = "you-cannot-pass-or-shall.html"
title = "You cannot pass... or shall?"

